apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: docker-registry-gui
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: docker-gui.rcomanne.nl

patchesStrategicMerge:
  - add_pull_secret.yaml